---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
      - key: "podinfoUIColor"
        value: "#34577c"
        version: "v1"
      - key: "podinfoUIColor"
        value: "#ffdfd3"
        version: "v2"
