---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prod-secrets  
  namespace: app2
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: prod-secrets
  data:
  - secretKey: podinfoUIColor
    remoteRef:
      key: podinfoUIColor
      version: v1
